### ISSUE TITLE
Buildroot support

### ISSUE THREAD

**Issue by liftoff-sr** [mickael-guene/fdpic_manifest#1]
The slideshow mentioned buildroot support for ARM FDPIC ELF.  Does this exist, and if so where?

I am using the toolchain but want to streamline the integration with buildroot.  I am hoping to build the C runtime library under there also.

**Comment by mickael-guene** [comment]
Yes it exists but it's done and use by internal toolchain customer. And so it's not public.
 On my side I have just do some test for stm32f469 discovery board. But nothing ready to be published. You can use toolchain as an external one in buildroot. If I remember well it's quite easy to do.
